# Standards: 0.1
---
- name: Fact rocketchat user
  set_fact:
    rocketchat_user: "{{ rocketchat_user | default(homebrew_user) | default(ansible_user_id) }}"
  tags:
    - rocketchat

- become: "{{ (rocketchat_user != ansible_user_id) | bool }}"
  become_user: "{{ rocketchat_user }}"
  block:
    - name: Install required package
      ignore_errors: True
      homebrew_cask:
        name: rocket-chat
        greedy: True
        options: appdir=/Applications
        accept_external_apps: False
        state: upgraded
      tags:
        - rocketchat

    - name: Remove quarantine flag
      register: rocketchat_quarantine
      failed_when: rocketchat_quarantine.rc != 0 and "No such xattr" not in rocketchat_quarantine.stderr
      changed_when: rocketchat_quarantine.rc == 0
      command: xattr -d com.apple.quarantine /Applications/Rocket.Chat.app
      tags:
        - rocketchat

    - name: Start application
      when: rocketchat_started
      changed_when: False
      command: open -j /Applications/Rocket.Chat.app
      tags:
        - rocketchat

...
