# Standards: 0.1
---
- name: Kill rocketchat
  command: killall Rocket.Chat
  register: rocketchat_kill
  failed_when: rocketchat_kill.rc != 0 and "No matching processes belonging to you were found" not in rocketchat_kill.stderr
  become: "{{ (rocketchat_user != ansible_user_id) | bool }}"
  become_user: "{{ rocketchat_user }}"

- name: Start rocketchat
  when: rocketchat_started
  command: open -j /Applications/Rocket.Chat.app
  become: "{{ (rocketchat_user != ansible_user_id) | bool }}"
  become_user: "{{ rocketchat_user }}"

...
